name: agent
downdir: /opt/download
gamedir: /snapshot/area_game_data
userdata: /snapshot/area_user_data/1_1
user: 1001
group: 1001
net:
    ip: 0.0.0.0
    mgntPort: 45010
    dataPort: 45011
    tls:
        cert: ./misc/server.crt
        key: ./misc/server.key
auth:
    username: vrviu@sz
    password: 2NxWjhYydQGbjtxjPxwT++hGkKz98txmt2I5q4R4DwY=
    factor: 63e9d1ee
control:
    cacheSize: 500 # unit is MB
    maxActive: 10
